esphome:
  name: "mitch-personal-status-display"
  friendly_name: "Mitch's Personal Status Display"
  on_boot:
    priority: 600
    then:
      - delay: 1s
      - lambda: |-
          id(status_change_time) = ::time(nullptr);
      - if:
          condition:
            or:
              - lvgl.page.is_showing: page_screensaver
              - lvgl.is_paused
              - light.is_off: light_backlight
          then:
            - light.turn_on: light_backlight
            - lvgl.resume
            - lvgl.page.show: page_main
      - script.execute: update_display

packages:
  burnin: !include includes/burnin.esphome.yaml
  constants: !include includes/constants.esphome.yaml
  fonts: !include includes/fonts.esphome.yaml
  hardware: !include includes/hardware.esphome.yaml
  logic: !include includes/logic.esphome.yaml
  ui: !include includes/ui.esphome.yaml

api:
  encryption:
    key: !secret api_encryption_key

logger:
  level: DEBUG
  logs:
    number: NONE

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: homeassistant
    id: ha_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

