font:
  - file: 'gfonts://Itim'
    id: font_itim_50
    size: 50
    glyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz'
  - file: 'gfonts://Itim'
    id: font_itim_24
    size: 24
    glyphs: '0123456789:APM '
  - file: 'gfonts://Roboto'
    id: font_roboto_16
    size: 16
    glyphs: '0123456789:APMhm() '
  - file: 'gfonts://Roboto'
    id: font_roboto_12
    size: 12
    glyphs: '0123456789:APM '
  - file: "gfonts://Material+Symbols+Outlined"
    id: font_icons_150
    size: 150
    glyphs: [
      "${icon_sleeping}",
      "${icon_working}",
      "${icon_gaming}",
      "${icon_busy}",
      "${icon_meeting}",
      "${icon_home}",
      "${icon_away}"
    ]
  - file: "gfonts://Material+Symbols+Outlined"
    id: font_icons_24
    size: 24
    glyphs: [
      "${icon_clock}"
    ]